on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kaczmarj/apptainer
      options: --privileged
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: build
        run: /bin/sh build.sh